# Generated by Django 3.1.7 on 2021-03-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('departureTime', models.DateTimeField()),
                ('arrivalTime', models.DateTimeField()),
                ('actionEndTime', models.DateTimeField()),
                ('fireStationArrivalTime', models.DateTimeField()),
                ('incidentType', models.CharField(max_length=1000)),
                ('incidentPlace', models.CharField(max_length=20)),
                ('sectionCommander', models.CharField(max_length=10)),
                ('actionCommander', models.CharField(max_length=10)),
                ('driver', models.CharField(max_length=10)),
                ('perpetrator', models.CharField(max_length=1000)),
                ('victim', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=2000)),
                ('counter', models.CharField(max_length=10)),
                ('distance', models.CharField(max_length=10)),
            ],
        ),
    ]
