# Generated by Django 3.1.7 on 2021-03-28 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='privateid',
            field=models.CharField(default=models.CharField(max_length=10, primary_key=True, serialize=False), max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='section',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='actionCommander',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='actionEndTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 15, 47, 29, 445407)),
        ),
        migrations.AlterField(
            model_name='report',
            name='arrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 15, 47, 29, 445407)),
        ),
        migrations.AlterField(
            model_name='report',
            name='counter',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='departureTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 15, 47, 29, 445407)),
        ),
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='report',
            name='distance',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='driver',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='fireStationArrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 15, 47, 29, 445407)),
        ),
        migrations.AlterField(
            model_name='report',
            name='incidentPlace',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='incidentType',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='perpetrator',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='sectionCommander',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='victim',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
