# Generated by Django 3.1.7 on 2021-03-28 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20210328_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='actionEndTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 15, 54, 32, 884053)),
        ),
        migrations.AlterField(
            model_name='report',
            name='arrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 15, 54, 32, 884053)),
        ),
        migrations.AlterField(
            model_name='report',
            name='departureTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 15, 54, 32, 884053)),
        ),
        migrations.AlterField(
            model_name='report',
            name='fireStationArrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 15, 54, 32, 884053)),
        ),
        migrations.AlterField(
            model_name='report',
            name='incidentPlace',
            field=models.CharField(default='', max_length=50),
        ),
    ]
