# Generated by Django 3.1.7 on 2021-03-28 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_auto_20210328_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='privateid',
            new_name='reportid',
        ),
        migrations.AddField(
            model_name='report',
            name='stationid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='actionEndTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 17, 12, 31, 580223)),
        ),
        migrations.AlterField(
            model_name='report',
            name='arrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 17, 12, 31, 580223)),
        ),
        migrations.AlterField(
            model_name='report',
            name='departureTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 17, 12, 31, 580223)),
        ),
        migrations.AlterField(
            model_name='report',
            name='fireStationArrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 17, 12, 31, 580223)),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
