# Generated by Django 3.1.7 on 2021-04-17 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20210328_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firefighter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=25)),
                ('lastName', models.CharField(default='', max_length=25)),
                ('stationid', models.CharField(default='', max_length=10)),
                ('isDriver', models.BooleanField(default=False)),
                ('isSectionCommander', models.BooleanField(default=False)),
                ('isActionCommander', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='actionEndTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 16, 30, 55, 444495)),
        ),
        migrations.AlterField(
            model_name='report',
            name='arrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 16, 30, 55, 444495)),
        ),
        migrations.AlterField(
            model_name='report',
            name='departureTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 16, 30, 55, 444495)),
        ),
        migrations.AlterField(
            model_name='report',
            name='fireStationArrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 16, 30, 55, 444495)),
        ),
    ]
