# Generated by Django 3.1.7 on 2021-04-17 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_auto_20210417_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='counter',
            new_name='odometer',
        ),
        migrations.AlterField(
            model_name='report',
            name='actionEndTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 18, 46, 22, 594789)),
        ),
        migrations.AlterField(
            model_name='report',
            name='arrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 18, 46, 22, 594789)),
        ),
        migrations.AlterField(
            model_name='report',
            name='departureTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 18, 46, 22, 594789)),
        ),
        migrations.AlterField(
            model_name='report',
            name='fireStationArrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 18, 46, 22, 594789)),
        ),
    ]
