# Generated by Django 3.1.7 on 2021-04-18 16:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporter', '0009_auto_20210418_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firestation',
            name='ownerid',
        ),
        migrations.AlterField(
            model_name='report',
            name='actionEndTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 32, 5, 396295)),
        ),
        migrations.AlterField(
            model_name='report',
            name='arrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 32, 5, 396295)),
        ),
        migrations.AlterField(
            model_name='report',
            name='departureTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 32, 5, 396295)),
        ),
        migrations.AlterField(
            model_name='report',
            name='fireStationArrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 32, 5, 396295)),
        ),
        migrations.CreateModel(
            name='FirestationMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('memberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.firestation')),
            ],
        ),
    ]
