# Generated by Django 3.1.7 on 2021-05-30 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20210530_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='actionCommander',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='actionEndTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 21, 58, 34, 968164)),
        ),
        migrations.AlterField(
            model_name='report',
            name='arrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 21, 58, 34, 968164)),
        ),
        migrations.AlterField(
            model_name='report',
            name='departureTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 21, 58, 34, 968164)),
        ),
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='distance',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='driver',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='fireStationArrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 21, 58, 34, 968164)),
        ),
        migrations.AlterField(
            model_name='report',
            name='incidentPlace',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='incidentType',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='odometer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='perpetrator',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportid',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='section',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='sectionCommander',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='stationid',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='victim',
            field=models.TextField(default=''),
        ),
    ]
